stages:
  - build
  - deploy

# Use a specific tag to target the runner we just configured.
build_iso:
  stage: build
  tags:
    - acreetionos-iso
  script:
    - echo "Updating system and installing dependencies..."
    - sudo pacman -Syu --noconfirm git archiso
    
    # Clone the archiso profile from the specified URL.
    - echo "Cloning the archiso profile..."
    - git clone https://gitlab.acreetionos.org/natalie/acreetionos-gnome.git
    
    # Move into the cloned directory to build from there.
    - cd acreetionos-gnome
    
    # Build the ISO using mkarchiso with sudo.
    - echo "Building AcreetionOS ISO..."
    - sudo mkarchiso -v -o ../output .

  artifacts:
    paths:
      - output/*.iso
    name: "acreetionos-gnome-iso-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 week

deploy_iso:
  stage: deploy
  when: manual
  tags:
    - acreetionos-iso
  script:
    - echo "Deployment of AcreetionOS ISO complete."
  dependencies:
    - build_iso