stages:
  - build
  - deploy

build_iso:
  stage: build
  tags:
    - acreetionos-gnome # This tag ensures the job runs on your specific runner.
  script:
    - echo "Updating system and installing dependencies..."
    - sudo pacman -Syu --noconfirm git archiso
    - echo "Cloning the archiso profile..."
    - git clone https://gitlab.acreetionos.org/natalie/acreetionos-gnome.git
    - cd acreetionos-gnome
    - echo "Building AcreetionOS ISO..."
    - sudo mkarchiso -v -o ../output .
  artifacts:
    paths:
      - output/*.iso
    name: "acreetionos-gnome-iso-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 week

deploy_iso:
  stage: deploy
  when: manual
  tags:
    - acreetionos-gnome # The deploy job also needs to run on this specific runner.
  script:
    - echo "Deployment of AcreetionOS ISO complete."
    # Your deployment commands would go here.
  dependencies:
    - build_iso