name: Build and Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Arch Linux
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: pkgbuild
          
      - name: Install Dependencies
        run: |
          sudo pacman -Sy --noconfirm archiso base-devel # Add other packages you need
        
      - name: Build ISO
        run: |
          chmod +x build.sh
          ./build.sh
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/*
            *.zip
            *.tar.gz
            *.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
